/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
  const express = require('express');
  const bodyParser = require('body-parser');
  const fs=require("fs");
  
  const app = express();
  
  app.use(bodyParser.json());


  function findEle(arr,id) {
    for (let i = 0; i < arr.length; i++) {
      if(arr[i].id==id) {
        return i;
      }      
    }
    return -1;
  }

  function deleteEle(arr,id) {
    const newArr=[];
    for (let i = 0; i < arr.length; i++) {
      if(arr[i].id!=id) {
        newArr.push(arr[i]);
      }      
    }
    return newArr;
  }

  app.get('/todos',function(req,res) {
    fs.readFile("todos.json","utf8",function (err,data) {
      if(err) throw err;
        // data may be in the form of string so we need to change it the form of json
        // that is what we did 
        res.status(200).json(JSON.parse(data));
    })
  })


  app.get('/todos/:id',(req,res)=>{
    fs.readFile("todos.json","utf-8",function(err,data) {
      if(err) throw err;
      const id=parseInt(req.params.id);
      const todo=JSON.parse(data);
      const idx=findEle(todo,id);
      if(idx===-1) return res.status(404).send();
      
      res.status(200).json(todo[idx]);
    })    
  })

  app.post("/todos",function(req,res) {
    const newTodo={
        id:Math.floor(Math.random()*1000000),
        title:req.body.title,
        description:req.body.description,
    }

    fs.readFile("todos.json","utf-8",(err,data)=> {
      if(err) throw err;
      let todo=JSON.parse(data);
      todo.push(newTodo);
      fs.writeFile("todos.json",JSON.stringify(todo),(err) => {
        if(err) throw err;
        res.status(201).send(newTodo);            
      })
    })
  })

  app.put("/todos/:id",(req,res) => {
    fs.readFile("todos.json","utf-8",(err,data)=>{
      if(err) throw err;
      let todo=JSON.parse(data);
      const id=parseInt(req.params.id);
      const todoIdx=findEle(todo,id);
      if(todoIdx===-1) return res.status(404).send();
      const updatedTodo={
        id:id,
        title:req.body.title,
        description:req.body.description,
      }
      todo[todoIdx]=updatedTodo;
      fs.writeFile("todos.json",JSON.stringify(todo),(err) => {
        if(err) throw err;
        res.status(200).send(updatedTodo);            
      });
    });
  });

  app.delete("/todos/:id",(req,res) => {
    fs.readFile("todos.json","utf-8",(err,data)=>{
      if(err) throw err;
      let todo=JSON.parse(data);
      const id=parseInt(req.params.id);
      const todoIdx=findEle(todo,id);
      if(todoIdx===-1) return res.status(404).send();

      todo=deleteEle(todo,id);
      fs.writeFile("todos.json",JSON.stringify(todo),(err) => {
        if(err) throw err;
        res.status(200).send();            
      });
    });
  })


  app.use((req,res)=> {
    res.status(404).send();
  })




  
  module.exports = app;